name: ImanAI API

on:
  repository_dispatch:
    types: [register, chat, balance]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run
        env:
          ACTION: ${{ github.event.action }}
          API_KEY: ${{ github.event.client_payload.api_key }}
          USER_NAME: ${{ github.event.client_payload.customer_name }}
          USER_EMAIL: ${{ github.event.client_payload.customer_email }}
          USER_PLAN: ${{ github.event.client_payload.plan }}
          USER_MESSAGE: ${{ github.event.client_payload.message }}
        run: python api_handler.py
